### ISSUE TITLE
[Feature] Add Before and After hooks for Memory chain and Procedures chain

### ISSUE THREAD

**Issue by valentimarco** [zAlweNy26/ts-cat#17]
Adding before and After hooks for the 2 chains of the cat so ppl can do stuff like check the response of the llm and apply guardrails

**Comment by zAlweNy26** [comment]
Hi and thanks for the issue, can you please point the lines of code where would you like to add these two hooks?
I'd like to know if we are talking about the same thing.

**Comment by valentimarco** [comment]
https://github.com/zAlweNy26/ts-cat/blob/main/src/looking_glass/agent-manager.ts#L175
https://github.com/zAlweNy26/ts-cat/blob/main/src/looking_glass/agent-manager.ts#L188

**Comment by zAlweNy26** [comment]
What arguments do you think should be passed to the hooks?
